# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd00c297e09fa2613f5e6bf6c33189a7304d08e26b3660aee71ff8140655ecd584a0336b8bbf6535bce10c424dd9ffc9ea56452081fe7d0cd4c4eb4b9f3263ca

test:
  secret_key_base: a2c8d3b433615f4bf1ed543c1ae1cdd579a495bf4225df51f33aa1405bedb5be0089c8a25e7f95c87960d00ff9d1125ecddd73dea7f6217754a265b0c2e4916a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
